table_setting = {
    'auto_size_columns': False,
    'justification': 'left',
    # 'num_rows': 24,
    'alternating_row_color': '#0E7477',
    'expand_y': True,
    'expand_x': True,
    # 'vertical_scroll_only': False,
    'enable_events': True,
    'row_height': 35,
    'font': '_ 12',
    'header_font': '_ 9',
    'header_border_width': 1,
    # 'visible_column_map': None,
    # 'def_col_width': 10,
    # 'max_col_width': 20,
    # 'select_mode': None,
    # 'display_row_numbers': False,
    # 'text_color': None,
    # 'background_color': None,
    # 'selected_row_colors': (None, None),
    # 'header_text_color': None,
    # 'header_background_color': None,
    # 'header_relief': None,
    # 'row_colors': None,
    # 'hide_vertical_scroll': False,
    # 'border_width': None,
    # 'sbar_trough_color': None,
    # 'sbar_background_color': None,
    # 'sbar_arrow_color': None,
    # 'sbar_width': None,
    # 'sbar_arrow_width': None,
    # 'sbar_frame_color': None,
    # 'sbar_relief': None,
    'enable_click_events': True,
    # 'right_click_selects': False,
    # 'bind_return_key': False,
    # 'pad': None,
    # 'tooltip': None,
    # 'right_click_menu': None,
    # 'visible': True,
}

tab_setting = {
    # 'title_color': None,
    # 'background_color': None,
    # 'font': None,
    # 'pad': None,
    # 'disabled': False,
    # 'border_width': None,
    # 'tooltip': None,
    # 'right_click_menu': None,
    # 'expand_x': False,
    # 'expand_y': False,
    # 'visible': True,
    'element_justification': 'center',
}

input_setting = {
    'size': (25, 1),
    # 'auto_size_text': True,
    # 'enable_events': False,
    # 'relief': sg.RELIEF_SOLID,
    'font': ('_', 12),
    # 'text_color': None,
    # 'background_color': None,
    # 'border_width': 10,
    'justification': 'left',
    # 'pad': None,
    # 'key': None,
    # 'right_click_menu': None,
    # 'expand_x': True,
    # 'expand_y': False,
    # 'grab': None,
    # 'tooltip': None,
    # 'visible': True,
    # 'metadata': None
}

drop_down_setting = {
    # 'default_value': "Не выбрано",
    'size': (24, 1),
    # 'auto_size_text': None,
    # 'background_color': None,
    # 'text_color': None,
    # 'button_background_color': None,
    # 'button_arrow_color': None,
    # 'bind_return_key': False,
    # 'change_submits': False,
    # 'enable_events': False,
    # 'disabled': False,
    # 'key': None,
    # 'pad': None,
    # 'expand_x': False,
    # 'expand_y': False,
    # 'tooltip': None,
    # 'readonly': False,
    'font': ('_', 12),
    # 'visible': True,
    # 'metadata': None
}

text_setting = {
    'size': 20,
    # 'auto_size_text': None,
    # 'enable_events': False,
    # 'relief': None,
    'font': '_ 10',
    # 'text_color': None,
    # 'background_color': None,
    # 'border_width': None,
    # 'justification': None,
    # 'pad': None,
    # 'right_click_menu': None,
    # 'expand_x': False,
    # 'expand_y': False,
    # 'grab': None,
    # 'tooltip': None,
    # 'visible': True,
    # 'metadata': None
}

multiline_setting = {
    # 'disabled': False,
    # 'autoscroll': False,
    # 'border_width': None,
    'size': (24, 3),
    # 'auto_size_text': None,
    # 'background_color': None,
    # 'text_color': None,
    # 'horizontal_scroll': False,
    # 'change_submits': False,
    # 'enable_events': False,
    # 'do_not_clear': True,
    # 'write_only': False,
    # 'auto_refresh': False,
    # 'reroute_stdout': False,
    # 'reroute_stderr': False,
    # 'reroute_cprint': False,
    # 'echo_stdout_stderr': False,
    # 'focus': False,
    'font': '_ 12',
    # 'pad': None,
    # 'tooltip': None,
    # 'justification': None,
    # 'no_scrollbar': False,
    # 'sbar_trough_color': None,
    # 'sbar_background_color': None,
    # 'sbar_arrow_color': None,
    # 'sbar_width': None,
    # 'sbar_arrow_width': None,
    # 'sbar_frame_color': None,
    # 'sbar_relief': None,
    # 'expand_x': False,
    # 'expand_y': False,
    # 'rstrip': True,
    # 'right_click_menu': None,
    # 'visible': True,
    # 'metadata': None
}
