table_setting = {
    'auto_size_columns': False,
    'justification': 'left',
    # 'num_rows': 24,
    'alternating_row_color': '#0E7477',
    'expand_y': True,
    'expand_x': True,
    # 'vertical_scroll_only': False,
    'enable_events': True,
    'row_height': 35,
    'font': '_ 12',
    'header_font': '_ 9',
    'header_border_width': 1,
    # 'visible_column_map': None,
    # 'def_col_width': 10,
    # 'max_col_width': 20,
    # 'select_mode': None,
    # 'display_row_numbers': False,
    # 'text_color': None,
    # 'background_color': None,
    # 'selected_row_colors': (None, None),
    # 'header_text_color': None,
    # 'header_background_color': None,
    # 'header_relief': None,
    # 'row_colors': None,
    # 'hide_vertical_scroll': False,
    # 'border_width': None,
    # 'sbar_trough_color': None,
    # 'sbar_background_color': None,
    # 'sbar_arrow_color': None,
    # 'sbar_width': None,
    # 'sbar_arrow_width': None,
    # 'sbar_frame_color': None,
    # 'sbar_relief': None,
    # 'enable_click_events': False,
    # 'right_click_selects': False,
    # 'bind_return_key': False,
    # 'pad': None,
    # 'tooltip': None,
    # 'right_click_menu': None,
    # 'visible': True,
}

tab_setting = {
    # 'title_color': None,
    # 'background_color': None,
    # 'font': None,
    # 'pad': None,
    # 'disabled': False,
    # 'border_width': None,
    # 'tooltip': None,
    # 'right_click_menu': None,
    # 'expand_x': False,
    # 'expand_y': False,
    # 'visible': True,
    'element_justification': 'center',
}
